import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.patches import Rectangle
import math

# Load the data generated by your C++ Navigation Stack
try:
    map_data = pd.read_csv("map.csv")
    global_path = pd.read_csv("global_path.csv")
    robot_path = pd.read_csv("robot_path.csv")
except FileNotFoundError:
    print("Error: Run the C++ program first to generate the CSV files!")
    exit()

# Setup the Map
fig, ax = plt.subplots(figsize=(10, 10))
ax.set_xlim(-1, 10)
ax.set_ylim(-1, 10)
ax.set_title("Full Navigation Stack: A* Global + DWA Local", fontsize=16)
ax.set_facecolor("white") # Clean background

# 1. DRAW THE WALLS (Like your image: Gray border, dark interior)
# A grid cell is 1x1. We draw a 1x1 rectangle for every wall coordinate.
for i in range(len(map_data)):
    wx, wy = map_data['x'].iloc[i], map_data['y'].iloc[i]
    # We center the 1x1 block on the coordinate
    wall = Rectangle((wx - 0.5, wy - 0.5), 1.0, 1.0, 
                     facecolor='#333333', edgecolor='#999999', linewidth=4)
    ax.add_patch(wall)

# 2. DRAW THE GLOBAL A* PATH (Light blue line with dots)
ax.plot(global_path['x'], global_path['y'], 
        color='#66c2ff', linewidth=3, marker='o', markersize=4, label='A* Global Path')

# Mark Start and Goal
ax.plot(global_path['x'].iloc[0], global_path['y'].iloc[0], 'go', markersize=8, label="Start")
ax.plot(global_path['x'].iloc[-1], global_path['y'].iloc[-1], 'ro', markersize=8, label="Goal")

# 3. SETUP THE ROBOT
robot_size = 0.6
# Dark blue square for the robot base
robot_patch = Rectangle((0, 0), robot_size, robot_size, angle=0.0, color='#004488', zorder=5)
ax.add_patch(robot_patch)

# Red line showing the exact path the DWA robot actually drove
trail_line, = ax.plot([], [], color='red', linewidth=2, alpha=0.7, label='DWA Executed Path')
history_x, history_y = [], []

def update(frame):
    x = robot_path['x'].iloc[frame]
    y = robot_path['y'].iloc[frame]
    theta = robot_path['theta'].iloc[frame]
    
    # Offset the matplotlib rectangle so it rotates around its true center
    offset_x = x - (robot_size / 2) * math.cos(theta) + (robot_size / 2) * math.sin(theta)
    offset_y = y - (robot_size / 2) * math.sin(theta) - (robot_size / 2) * math.cos(theta)
    
    robot_patch.set_xy((offset_x, offset_y))
    robot_patch.angle = math.degrees(theta) 
    
    history_x.append(x)
    history_y.append(y)
    trail_line.set_data(history_x, history_y)
    
    return robot_patch, trail_line

# Run the animation at 50ms per frame
ani = animation.FuncAnimation(fig, update, frames=len(robot_path), interval=20, blit=True)
plt.legend(loc="upper left")
plt.show()